### ISSUE TITLE
mod_degree is not zero despite context_original and context_mod are the same?

### ISSUE THREAD

**Issue by bzhangj13zzz** [kevinwu23/StanfordClashEval#2]
Thanks to the authors for releasing the dataset. However, I am slightly confused about the 'mod_degree' here. Specifically, I found a few entries in the dataset that have the same `context_original` and `context_mod` yet the `mod_degree` is non-zero and the `answer_original` and `answer_mod` are different as well.

This is the code I used to check the dataset

```python

from datasets import load_dataset

dataset = load_dataset('kewu93/ClashEval', trust_remote_code=True)
dataset = dataset['test']

count = 0

for entry in dataset:
    if entry['context_original'] == entry['context_mod']:
        if entry['answer_mod'] != entry['answer_original']:
            count += 1

print(count)
```
From what I understand, if the context is not altered, it should mean there is no modification and the answers should stay unchanged?

I found there are 88 such entries. This may raise concerns about the validity of the dataset, especially the modification part. Or maybe I have misunderstood the way this dataset is curated. It will be much appreciated if it can be clarified, many thanks!

**Comment by kevinwu23** [comment]
Thank you for bringing this issue to us! These contexts should not be the same, and the issue is attributable to the fact that our LLM-based perturbations may change the original statement, which creates a silent error when we perform the substitution. This affects a total of 12 (<1% total) questions between the drugs and news dataset, which we will remove from our eval dataset for now. We will deploy a fix to add these back in shortly after. Thanks again for pointing this out.

**Comment by bzhangj13zzz** [comment]
Thank you for your response!
