### ISSUE TITLE
How to reproduce the model responses' parquet files

### ISSUE THREAD

**Issue by xdotli** [kevinwu23/StanfordClashEval#3]
I wonder how you guys arrive at the results as there are 10179 rows in dataset parquet but 11258 rows in gpt4.pqt.

**Comment by kevinwu23** [comment]
Thank you for bringing this to our attention -- 
As per a previous issue, we have removed a small handful (12) of questions due to a silent error in the modification process. We will aim to reproduce those in a v2.0 of ClashEval so the total sample is the same as before. In the meantime, there will be model responses to these removed questions, so please ignore them in your analyses for consistency.
Please let us know if you have any other questions!
